In [13]:
print("hello python")

hello python


In [14]:
import numpy as np

In [15]:
a=np.array([2,3,5,8,6,4])

In [16]:
a

array([2, 3, 5, 8, 6, 4])

In [17]:
a.ndim

1

In [18]:
b=np.array([10,20,30,40,50,60])

In [19]:
b

array([10, 20, 30, 40, 50, 60])

In [20]:
c=np.array([(1,2,3),(4,5,6)])

In [21]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [25]:
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [26]:
np.random.rand(3,4)

array([[0.22544244, 0.29021149, 0.80998976, 0.263189  ],
       [0.15949109, 0.81436269, 0.99335022, 0.87079142],
       [0.74790176, 0.14907304, 0.73656783, 0.91708877]])

In [27]:
np.random.rand(2,3)*100

array([[86.76184797,  5.47447555, 62.30939509],
       [47.24913506, 91.67502949, 95.34397089]])

In [29]:
np.random.randint(5,size=(2,3))

array([[2, 2, 1],
       [1, 1, 2]])

In [30]:
np.random.randint(5,size=(2,3))

array([[0, 1, 1],
       [2, 4, 2]])

In [31]:
a.size

6

In [32]:
a.shape

(6,)

In [35]:
a.datatype

AttributeError: 'numpy.ndarray' object has no attribute 'datatype'

In [36]:
a.dtype

dtype('int32')

In [37]:
np.copy(b)

array([10, 20, 30, 40, 50, 60])

In [39]:
a.sort()

In [40]:
a

array([2, 3, 4, 5, 6, 8])

In [41]:
a+b

array([12, 23, 34, 45, 56, 68])

In [42]:
b-a

array([ 8, 17, 26, 35, 44, 52])

In [43]:
b/2

array([ 5., 10., 15., 20., 25., 30.])

In [44]:
a*4

array([ 8, 12, 16, 20, 24, 32])

In [45]:
np.append(a,2)

array([2, 3, 4, 5, 6, 8, 2])

In [46]:
np.insert(b,2,34)

array([10, 20, 34, 30, 40, 50, 60])

In [47]:
np.delete(b,3,axis=0)

array([10, 20, 30, 50, 60])

In [48]:
np.delete(c,2,axis=1)

array([[1, 2],
       [4, 5]])

In [49]:
np.concatenate((a,b),axis=0)

array([ 2,  3,  4,  5,  6,  8, 10, 20, 30, 40, 50, 60])

In [50]:
a[5]

8

In [51]:
v=np.array(([2,4,3],[5,5,6]))

In [52]:
v

array([[2, 4, 3],
       [5, 5, 6]])

In [53]:
v[:,2]

array([3, 6])

In [54]:
np.add(b,4)

array([14, 24, 34, 44, 54, 64])

In [55]:
np.sin(a)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,
        0.98935825])

In [56]:
np.tan(b)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493, -0.27190061,
        0.32004039])

In [57]:
np.tanh(c)

array([[0.76159416, 0.96402758, 0.99505475],
       [0.9993293 , 0.9999092 , 0.99998771]])

In [58]:
np.add(a,b)

array([12, 23, 34, 45, 56, 68])

In [59]:
np.mean(a,axis=0)

4.666666666666667

In [60]:
b.max(axis=0)

60

In [61]:
np.round(5.8)

6.0

In [62]:
np.floor(5.62)

5.0

In [63]:
a

array([2, 3, 4, 5, 6, 8])

In [64]:
np.log(b)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456])

In [65]:
np.sqrt(b)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])

In [66]:
np.power(a,5)

array([   32,   243,  1024,  3125,  7776, 32768], dtype=int32)